service: parallelerrors

plugins:
  - serverless-step-functions
  # - serverless-pseudo-parameters
  # - serverless-stack-output

# custom:
  # output:                       # Plugin: serverless-stack-output
  #   file: serverless-stack-output.json # toml, yaml, yml, json

package:
  individually: true
  exclude:
    - "**"                      # all files and directories

provider:
  name: aws
  runtime: python3.8
  logRetentionInDays: 30        # dont create infinite logs as they cost money

functions:
  Json:
    handler: handler.json
    package:
      include:
        - handler.py
  Pdf:
    handler: handler.pdf
    package:
      include:
        - handler.py
  HandleErrorSystem:
    handler: handler.error_system
    package:
      include:
        - handler.py
  HandleErrorUser:
    handler: handler.error_user
    package:
      include:
        - handler.py


stepFunctions:
  stateMachines:
    ParallelError:
      name: ParallelError
      definition:
        StartAt: Start
        States:
          Start:
            Type: Pass
            Next: Parallelize
          Parallelize:
            Type: Parallel
            Next: Done
            Catch:
            - ErrorEquals: ["UserError"]
              ResultPath: $.error
              Next: HandleErrorUser
            - ErrorEquals: ["SystemError"]
              ResultPath: $.error
              Next: HandleErrorSystem
            Branches:
              - StartAt: Json
                States:
                  Json:
                    Type: Task
                    Resource:
                      Fn::GetAtt: [Pdf, Arn]
                    End: true
              - StartAt: Pdf
                States:
                  Pdf:
                    Type: Task
                    Resource:
                      Fn::GetAtt: [Json, Arn]
                    End: true
          Done:
            Type: Pass
            End: true
          HandleErrorSystem:
            Type: Pass
            Next: DoneError
          HandleErrorUser:
            Type: Pass
            Next: DoneError
          DoneError:
            Type: Fail
            Cause: Error Occurred
                
  
